version: '2'
services:
  # postgresql:
  #   image: docker.io/bitnami/postgresql:latest
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #     - POSTGRESQL_USERNAME=bn_keycloak
  #     - POSTGRESQL_DATABASE=bitnami_keycloak
  #   volumes:
  #     - 'postgresql_data:/bitnami/postgresql'
  keycloak:
    image: docker.io/bitnami/keycloak:latest
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: true
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_NAME: keycloakdb
      KEYCLOAK_DATABASE_USER: admin
      KEYCLOAK_DATABASE_PASSWORD: 123
      KEYCLOAK_HTTP_PORT: 8085

    ports:
      - '9083:8085'
    networks: 
      - postgres_default
    # depends_on:
    #   - postgres
networks: 
    postgres_default:
      external: true