version: '3'  
services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    #restart: unless-stopped
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloakdb
      DB_USER: admin
      DB_PASSWORD: 123
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # KEYCLOAK_LOGLEVEL: DEBUG
      # ROOT_LOGLEVEL: DEBUG
    ports:
      - '9083:8080'
    networks: 
      - postgres_default
    command:
      - start-dev --hostname=http://myproduct.local/keycloak
    # depends_on:
    #   - postgres
networks: 
    postgres_default:
      external: true