version: "3"

# More info at https://github.com/oracle/opengrok/docker/
services:
  opengrok:
    image: opengrok/docker:latest
    container_name: opengrok-bco
    #user: 1000:1000
    ports: 
      - "8090:8080"
    environment:
      SYNC_PERIOD_MINUTES: '60'
    # Volumes store your data between container upgrades
    volumes:
       - '~/opengrok/src:/opengrok/src/'  # source code
       - '~/opengrok/data:/opengrok/data/'
       - '~/opengrok/etc:/opengrok/etc/'
#     networks: 
#         - nginx-examples_default

# networks: 
#     nginx-examples_default:
#         external: true