version: "3"

# More info at https://github.com/oracle/opengrok/docker/
services:
  opengrok:
    image: elkin5/opengrok-open
    container_name: opengrok-test
    ports: 
      - "8090:8080"
    environment:
      REINDEX: 30
    # Volumes store your data between container upgrades
    volumes:
       - '~/opengrok/src:/opengrok/src/'  # source code
       - '~/opengrok/data:/opengrok/data/'
       - '~/opengrok/etc:/opengrok/etc/'
#     networks: 
#         - nginx-examples_default

# networks: 
#     nginx-examples_default:
#         external: true