version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    # ports:
    #   - "5432:5432" comentados para que utilice la red host
    # user: 1000:1000
    # networks:
    #   - nginx-server_default
    # Este es el usuario root de la base de datos
    environment:
      # - POSTGRES_DB=keycloakdb nombre bd ppal
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
    volumes:
      - ~/postgresql:/var/lib/postgresql
      - ~/postgresql/data:/var/lib/postgresql/data
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '1.0'       # Limita el uso de CPU a 1 núcleo
          memory: 512M      # Limita la memoria a 512 MB
    command: >
      postgres -c max_connections=100
                -c shared_buffers=128MB
# networks: 
#     postgres_default:
#         external: true