version: "3.9"

services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    user: 1000:1000
    # networks:
    #   - nginx-server_default
    # Este es el usuario root de la base de datos
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    volumes:
      - ~/postgresql:/var/lib/postgresql
      - ~/postgresql/data:/var/lib/postgresql/data

# networks: 
#     nginx-server_default:
#         external: true