version: '3'

services: 
    redis:
        container_name: redis-container
        image: redis:6
        volumes: 
            - ./redis.conf:/usr/local/etc/redis/redis.conf
            - ~/redis-data:/data
        command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes #reescribe el CMD